version: '3'

services:
  postgresql:
    container_name: db_--pkg-name
    image: nogsantos/postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - PG_PASSWORD=${DB_PASSWORD}
      - DB_NAME=--pkg-name
    volumes:
      - ./postgres/scripts:/scripts:rw
      - ./postgres/data:/var/lib/postgresql:rw
