spring:
  application:
    name: ${APPLICATION_NAME}
    description: ${APPLICATION_DESCRIPTION}
    version: ${APPLICATION_VERSION}
    contact:
      name: ${CONTACT_NAME}
      site: ${CONTACT_SITE}
      email: ${CONTACT_EMAIL}
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://${DB_URL}}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: false
    show-sql: true
  flyway:
    password: ${DB_PASSWORD}
    url: ${DATABASE_URL:jdbc:postgresql://${DB_URL}}
    user: ${DB_USER}
    baseline-on-migrate: true
    enabled: true
    encoding: UTF-8
server:
  port: ${SERVER_PORT}
security:
  oauth2:
    client:
      client-id: ${JWT_CLIENT_ID}
      client-secret: ${JWT_CLIENT_SECRET}
